server:
  port: 8800
  mode: debug

logging:
  logLevel: 0  # -1 TRACE | 0 DEBUG | 1 INFO (default) | 2 WARN
  outputFormat: TEXT # TEXT | JSON (default)

discord:
  token: BOT_TOKEN
  botID: BOT_ID
  channels:
    groceries: 1084632136180572230
    tkGoods: 1146023101755293786
