server:
  port: 8800
  mode: debug

logging:
  logLevel: 0  # -1 TRACE | 0 DEBUG | 1 INFO (default) | 2 WARN
  outputFormat: TEXT # TEXT | JSON (default)

discord:
#  token: ${BOT_TOKEN}
  token: TVRFMU56TTFOemcwTVRnek16Z3dPREF5TXcuR19idmRKLmgtNGVHdS1NbTk2em9meXNKLXh3SUJ3aURIZ25fWGxpU0xvSmlZ
  botID: 1157357841833808023
  channels:
    groceries: 1084632136180572230
