server:
  port: 8800
  mode: release

logging:
  logLevel: 1 # -1 TRACE | 0 DEBUG | 1 INFO (default) | 2 WARN
  outputFormat: JSON # TEXT | JSON (default)

discord:
  token: BOT_TOKEN
  botID: BOT_ID
  channels:
    - name: groceries
      id: 1084632136180572230
      lineBreak: 20
    - name: freezer
      id: 1146023101755293786
      lineBreak: 18

database:
  sqlite: /data/roastbeef-swag.db
